name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Archive the data folder
      run: zip -r data.zip data
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: datazip
        path: data.zip
