name: Package Packs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_paks:

    runs-on: ubuntu-latest
    outputs:
      artifact_name: ${{ steps.set-artifact-name.outputs.name }}

    steps:
    - uses: actions/checkout@v4

    - name: Get short commit hash
      id: get-commit-hash
      run: echo "SHORT_HASH=${GITHUB_SHA::7}" >> $GITHUB_ENV
      
    - name: Rename dpack.mcmeta to pack.mcmeta
      run: mv dpack.mcmeta pack.mcmeta
    
    - name: Upload data artifact
      uses: actions/upload-artifact@v4
      with:
        name: Ithavollr_dpack-${{ env.SHORT_HASH }}
        path: |
          assets
          pack.mcmeta
        compression-level: 9

    - name: Rename rpack.mcmeta to pack.mcmeta
      run: mv rpack.mcmeta pack.mcmeta

    - name: Set asset artifact name
      id: set-artifact-name
      run: echo "name=Ithavollr_rpack-${{ env.SHORT_HASH }}" >> $GITHUB_OUTPUT

    - name: Upload asset artifact
      uses: actions/upload-artifact@v4
      with:
        name: Ithavollr_rpack-${{ env.SHORT_HASH }}
        path: |
          assets
          pack.mcmeta
          pack.png
        compression-level: 9

  update_client:
    needs: build_paks
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    # Get the authoritative zip file
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ needs.build_paks.outputs.artifact_name }}

    # Get the token from NokNokRok
    - name: Generate App Token
      uses: actions/create-github-app-token@v2
      id: app-token
      with:
        app-id: ${{ secrets.NOK_APP_ID }}
        private-key: ${{ secrets.NOK_PRIVATE_KEY }}

    - name: Checkout ClientModpack
      uses: actions/checkout@v4
      with:
        repository: Ithavollr/ClientModpack
        token: ${{ steps.app-token.outputs.token }}
        path: cmp

    - name: Deploy Artifacts
      run: |
        rm cmp/resourcepacks/Ithavollr_rpack.zip
        ls -al
        zip -r Ithavollr_rpack.zip ${{ needs.build_paks.outputs.artifact_name }}
        mv Ithavollr_rpack.zip cmp/resourcepacks/
        cd cmp
        git config --global user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
        git config --global user.email '${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com'
        git add .
        if git diff-index --quiet HEAD; then
          echo "No changes to commit."
        else
          git commit -m "Deploy ${{ needs.build_paks.outputs.artifact_name }}"
          git push
        fi
