name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_paks:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Get short commit hash
      id: get-commit-hash
      run: echo "short_hash=${GITHUB_SHA::7}" >> $GITHUB_ENV

    - name: Archive the data folder
      run: zip -r Ithavollr-dpack_${SHORT_HASH}.zip data

    - name: Archive the resource folder
      run: zip -r Ithavollr-rpack_${SHORT_HASH}.zip assets pack.mcmeta pack.png
      
    - name: Upload data artifact
      uses: actions/upload-artifact@v4
      with:
        name: Ithavollr-dpack_${{ env.short_hash }}
        path: Ithavollr-dpack.zip

    - name: Upload asset artifact
      uses: actions/upload-artifact@v4
      with:
        name: Ithavollr_rpack_${{ env.short_hash }}
        path: Ithavollr_rpack.zip
