name: Package Packs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_paks:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Get short commit hash
      id: get-commit-hash
      run: echo "SHORT_HASH=${GITHUB_SHA::7}" >> $GITHUB_ENV
      
    - name: Rename dpack.mcmeta to pack.mcmeta
      run: mv dpack.mcmeta pack.mcmeta
    
    - name: Upload data artifact
      id: upload-data-artifact
      uses: actions/upload-artifact@v4
      with:
        name: Ithavollr_dpack-${{ env.SHORT_HASH }}
        path: dpak_v61
        compression-level: 9
    - name: Zip data artifact
      run: zip -9r Ithavollr_dpack.zip dpak_v61

    - name: Rename rpack.mcmeta to pack.mcmeta
      run: mv rpack.mcmeta pack.mcmeta

    - name: Upload asset artifact
      id: upload-asset-artifact
      uses: actions/upload-artifact@v4
      with:
        name: Ithavollr_rpack-${{ env.SHORT_HASH }}
        path: assets_v46
        compression-level: 9
    - name: Zip asset artifact
      run: zip -9r Ithavollr_rpack.zip assets_v46

    - name: Stream asset artifact
      run: |
        curl -X POST \
          -H "Authorization: Bearer ${{ secrets.JENKINS_WEBHOOK_TOKEN }}" \
          -H "Content-Type: application/octet-stream" \
          --data-binary @Ithavollr_rpack.zip \
          ${{ secrets.JENKINS_URL }}/pacman-rpak
          
    - name: Stream data artifact
      run: |
        curl -X POST \
          -H "Authorization: Bearer ${{ secrets.JENKINS_WEBHOOK_TOKEN }}" \
          -H "Content-Type: application/octet-stream" \
          --data-binary @Ithavollr_dpack.zip \
          ${{ secrets.JENKINS_URL }}/pacman-dpak
