name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_paks:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Archive the data folder
      run: zip -r Ithavollr-dpack.zip data

    - name: Archive the resource folder
      run: zip -r Ithavollr_rpack000.zip assets
      
    - name: Upload data artifact
      uses: actions/upload-artifact@v4
      with:
        name: datazip
        path: Ithavollr-dpack.zip

    - name: Upload asset artifact
      uses: actions/upload-artifact@v4
      with:
        name: assetzip
        path: Ithavollr_rpack000.zip
