name: Package Packs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_paks:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Get short commit hash
      id: get-commit-hash
      run: echo "SHORT_HASH=${GITHUB_SHA::7}" >> $GITHUB_ENV
      
    - name: Rename dpack.mcmeta to pack.mcmeta
      run: mv dpack.mcmeta pack.mcmeta
    
    - name: Upload data artifact
      id: upload-data-artifact
      uses: actions/upload-artifact@v4
      with:
        name: Ithavollr_dpack-${{ env.SHORT_HASH }}
        path: |
          assets
          pack.mcmeta
        compression-level: 9

    - name: Rename rpack.mcmeta to pack.mcmeta
      run: mv rpack.mcmeta pack.mcmeta

    - name: Set asset artifact name
      id: set-artifact-name
      run: echo "name=Ithavollr_rpack-${{ env.SHORT_HASH }}" >> $GITHUB_OUTPUT

    - name: Upload asset artifact
      id: upload-asset-artifact
      uses: actions/upload-artifact@v4
      with:
        name: Ithavollr_rpack-${{ env.SHORT_HASH }}
        path: |
          assets
          pack.mcmeta
          pack.png
        compression-level: 9

    - name: Alert Jenkins
      if: success()
      run: |
        curl -X POST \
          -H "Content-Type: application/json" \
          -d '{
              "token":"${{ secrets.JENKINS_WEBHOOK_TOKEN }}",
              "run_id":"${{ github.run_id }}",
              "data_artifact_id":"${{ steps.upload-data-artifact.outputs.artifact-id }}",
              "asset_artifact_id":"${{ steps.upload-asset-artifact.outputs.artifact-id }}"
            }' \
            ${{ secrets.JENKINS_URL }}/pacman
